### PR TITLE
Run tests on Travis

### PR DESCRIPTION
**Pull request by RoanH**
*please wait a bit with merging this, I still want to confirm whether this works properly and intentionally push a failing test.

### CODE REVIEW

**Comment by JoostvanPinxten** [comment]
It indeed fails on the `make check` step now.

Side note: Are there only 2 tests to be executed?

**Comment by RoanH** [comment]
Seems like there is something going on with the SEP tests yeah, but another group member already said he knew what was going on there so I'm waiting for that.

Side note: There are two tests suites that get executed (one for each plugin), both test suites contain multiple tests.

**Comment by RoanH** [comment]
Still waiting for Travis, but the change should make it so that `make check` can now be executed from any build location which should fix the issue of the test files not being found. The tests will still fail however until #9 is merged, but that's fine since I wanted to push a failing test anyway to verify that Travis correctly exists with a failing exit code when a test fails.

If everything goes as expected I'll remove the draft status from this PR.

**Comment by RoanH** [comment]
Opening this up for review since everything appears to work correctly on Travis. The Travis build itself is still failing because of a failing test case which is fixed in #9.

**Comment by RoanH** [comment]
Small note, just heard that #16 fixes another test case so this build will probably still fail.

**Comment by RoanH** [comment]
That merge commit should pass on Travis CI as far as I know.

**Pull request merged**
