### PR TITLE
Refactor build scripts

### PR DESCRIPTION
**Pull request by kees-jan**
Refactoring the build scripts a bit.

The ultimate goal is to build both against scroom as referenced by the repo, and against the latest scroom, at least in my clone of the repo. Goals is to be able to detect regressions faster.

I'm not there yet, but this is a first step, and should be good to merge as-is.

Note: This builds on my previous pull-request (#14), mostly because I need an even newer version of scroom for this to actually work.

### CODE REVIEW

**Comment by kees-jan** [comment]
> This PR removes the pipette plugin again (just like #14). 

Well, yes. Because it contains the exact same commits.

> I think these should be in different pull requests and thus be removed from this pull request.

I would love to have done that, except that it is impossible without introducing a merge conflict (both pull requests need to change the referenced version of scroom)

> Additionally, these changes invalidate a large part of the documentation that the TU/e requires our group to write. As such, I kindly request this PR (just like #14) to not be merged, at least until all documentation our group has written has been graded by the TU/e.

I sympathize, but that would force me to manually port fixes you apply to pippete plugin to the main scroom repo (due to coding style differences). Can't we find a different solution? Like, for example, you creating a branch against which you wish to be graded?

**Comment by kees-jan** [comment]
Turns out the two pull requests actually are independent. That should make this one non-controversial.

Now we still have to resolve the issues with the other one.

**Comment by JoostvanPinxten** [comment]
I am in favor of merging this PR. However, I don't want to disturb the grading process (yet).

@LukeSerne Can you indicate when this organizational conflict should be resolved?

**Comment by kees-jan** [comment]
I was thinking about creating a `next` branch, to push work on while awaiting the grading process. Didn't get around to that yet, though.

**Comment by RoanH** [comment]
I don't think that there should be any issues anymore. We've had to submit a zipped copy of the codebase itself, I doubt that the graders will look at either the GitHub or GitLab repository for the grading process. And even if they have to they can just look at the `v1.1` tag.

**Pull request merged**
